spring:
  profiles:
    active: development
    # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Server configuration
  server:
    port: 8080