spring:
  profiles:
    active: development
    # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Server configuration
  server:
    port: 8080
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml


logging:
  level:
    liquibase: INFO
